[package]
name = "maya-tools-installer"
version = "0.1.0"
authors = ["Giorgio Pomettini <giorgio.pomettini@gmail.com>"]

[dependencies]
reqwest = "0.8.6"
os_type = "1.0.0"
dirs = "1.0.3"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
